name: 'Setup BinDiff'
description: 'Setup BinDiff (IDA Pro 9.0)'
author: 'dumbasPL'

inputs:
  version:
    description: 'BinDiff version'
    required: false
    default: 'latest'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'download'
  color: 'blue'